top_srcdir   = /usr/local/src/apache_normal/httpd-2.4.29
top_builddir = /usr/local/src/apache_normal/httpd-2.4.29
srcdir       = /usr/local/src/apache_normal/httpd-2.4.29/server/mpm/worker
builddir     = /usr/local/src/apache_normal/httpd-2.4.29/server/mpm/worker
VPATH        = /usr/local/src/apache_normal/httpd-2.4.29/server/mpm/worker

include $(top_srcdir)/build/special.mk
