top_srcdir   = /usr/local/src/github/Codebase/httpd-2.4.29
top_builddir = /usr/local/src/github/Codebase/httpd-2.4.29
srcdir       = /usr/local/src/github/Codebase/httpd-2.4.29/srclib
builddir     = /usr/local/src/github/Codebase/httpd-2.4.29/srclib
VPATH        = /usr/local/src/github/Codebase/httpd-2.4.29/srclib

BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
