top_srcdir   = /usr/local/src/github/Codebase/httpd-2.4.29
top_builddir = /usr/local/src/github/Codebase/httpd-2.4.29
srcdir       = /usr/local/src/github/Codebase/httpd-2.4.29/modules/core
builddir     = /usr/local/src/github/Codebase/httpd-2.4.29/modules/core
VPATH        = /usr/local/src/github/Codebase/httpd-2.4.29/modules/core

include $(top_srcdir)/build/special.mk

