top_srcdir   = /usr/local/src/apache_normal/httpd-2.4.29
top_builddir = /usr/local/src/apache_normal/httpd-2.4.29
srcdir       = /usr/local/src/apache_normal/httpd-2.4.29/os
builddir     = /usr/local/src/apache_normal/httpd-2.4.29/os
VPATH        = /usr/local/src/apache_normal/httpd-2.4.29/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
