top_srcdir   = /usr/local/src/apache/httpd-2.4.29
top_builddir = /usr/local/src/apache/httpd-2.4.29
srcdir       = /usr/local/src/apache/httpd-2.4.29/modules/http
builddir     = /usr/local/src/apache/httpd-2.4.29/modules/http
VPATH        = /usr/local/src/apache/httpd-2.4.29/modules/http

include $(top_srcdir)/build/special.mk

