top_srcdir   = /usr/local/src/apache_normal/httpd-2.4.29
top_builddir = /usr/local/src/apache_normal/httpd-2.4.29
srcdir       = /usr/local/src/apache_normal/httpd-2.4.29/modules
builddir     = /usr/local/src/apache_normal/httpd-2.4.29/modules
VPATH        = /usr/local/src/apache_normal/httpd-2.4.29/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

