top_srcdir   = /usr/local/src/github/Codebase/httpd-2.4.29
top_builddir = /usr/local/src/github/Codebase/httpd-2.4.29
srcdir       = /usr/local/src/github/Codebase/httpd-2.4.29/modules/echo
builddir     = /usr/local/src/github/Codebase/httpd-2.4.29/modules/echo
VPATH        = /usr/local/src/github/Codebase/httpd-2.4.29/modules/echo

include $(top_srcdir)/build/special.mk

