top_srcdir   = /usr/local/src/apache_normal/httpd-2.4.29
top_builddir = /usr/local/src/apache_normal/httpd-2.4.29
srcdir       = /usr/local/src/apache_normal/httpd-2.4.29/modules/arch/unix
builddir     = /usr/local/src/apache_normal/httpd-2.4.29/modules/arch/unix
VPATH        = /usr/local/src/apache_normal/httpd-2.4.29/modules/arch/unix

include $(top_srcdir)/build/special.mk

