top_srcdir   = /usr/local/src/github/Codebase/httpd-2.4.29
top_builddir = /usr/local/src/github/Codebase/httpd-2.4.29
srcdir       = /usr/local/src/github/Codebase/httpd-2.4.29/modules/debugging
builddir     = /usr/local/src/github/Codebase/httpd-2.4.29/modules/debugging
VPATH        = /usr/local/src/github/Codebase/httpd-2.4.29/modules/debugging
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
