top_srcdir   = /usr/local/src/github/Codebase/httpd-2.4.29
top_builddir = /usr/local/src/github/Codebase/httpd-2.4.29
srcdir       = /usr/local/src/github/Codebase/httpd-2.4.29/server/mpm/prefork
builddir     = /usr/local/src/github/Codebase/httpd-2.4.29/server/mpm/prefork
VPATH        = /usr/local/src/github/Codebase/httpd-2.4.29/server/mpm/prefork
include $(top_srcdir)/build/special.mk
