top_srcdir   = /usr/local/src/apache_normal/httpd-2.4.29
top_builddir = /usr/local/src/apache_normal/httpd-2.4.29
srcdir       = /usr/local/src/apache_normal/httpd-2.4.29/modules/generators
builddir     = /usr/local/src/apache_normal/httpd-2.4.29/modules/generators
VPATH        = /usr/local/src/apache_normal/httpd-2.4.29/modules/generators

include $(top_srcdir)/build/special.mk

