top_srcdir   = /usr/local/src/github/Codebase/httpd-2.4.29
top_builddir = /usr/local/src/github/Codebase/httpd-2.4.29
srcdir       = /usr/local/src/github/Codebase/httpd-2.4.29/modules/loggers
builddir     = /usr/local/src/github/Codebase/httpd-2.4.29/modules/loggers
VPATH        = /usr/local/src/github/Codebase/httpd-2.4.29/modules/loggers

include $(top_srcdir)/build/special.mk

