top_srcdir   = /usr/local/src/apache/httpd-2.4.29
top_builddir = /usr/local/src/apache/httpd-2.4.29
srcdir       = /usr/local/src/apache/httpd-2.4.29/modules/aaa
builddir     = /usr/local/src/apache/httpd-2.4.29/modules/aaa
VPATH        = /usr/local/src/apache/httpd-2.4.29/modules/aaa

include $(top_srcdir)/build/special.mk

