top_srcdir   = /usr/local/src/apache/httpd-2.4.29
top_builddir = /usr/local/src/apache/httpd-2.4.29
srcdir       = /usr/local/src/apache/httpd-2.4.29/server/mpm/event
builddir     = /usr/local/src/apache/httpd-2.4.29/server/mpm/event
VPATH        = /usr/local/src/apache/httpd-2.4.29/server/mpm/event
include $(top_srcdir)/build/special.mk
