top_srcdir   = /usr/local/src/apache/httpd-2.4.29
top_builddir = /usr/local/src/apache/httpd-2.4.29
srcdir       = /usr/local/src/apache/httpd-2.4.29/server/mpm
builddir     = /usr/local/src/apache/httpd-2.4.29/server/mpm
VPATH        = /usr/local/src/apache/httpd-2.4.29/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
