top_srcdir   = /usr/local/src/apache_normal/httpd-2.4.29
top_builddir = /usr/local/src/apache_normal/httpd-2.4.29
srcdir       = /usr/local/src/apache_normal/httpd-2.4.29/modules/proxy
builddir     = /usr/local/src/apache_normal/httpd-2.4.29/modules/proxy
VPATH        = /usr/local/src/apache_normal/httpd-2.4.29/modules/proxy
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
#SUBDIRS = balancers
include $(top_srcdir)/build/special.mk
