top_srcdir   = /usr/local/src/github/Codebase/httpd-2.4.29
top_builddir = /usr/local/src/github/Codebase/httpd-2.4.29
srcdir       = /usr/local/src/github/Codebase/httpd-2.4.29/modules/mappers
builddir     = /usr/local/src/github/Codebase/httpd-2.4.29/modules/mappers
VPATH        = /usr/local/src/github/Codebase/httpd-2.4.29/modules/mappers

include $(top_srcdir)/build/special.mk

