top_srcdir   = /usr/local/src/apache/httpd-2.4.29
top_builddir = /usr/local/src/apache/httpd-2.4.29
srcdir       = /usr/local/src/apache/httpd-2.4.29/modules/filters
builddir     = /usr/local/src/apache/httpd-2.4.29/modules/filters
VPATH        = /usr/local/src/apache/httpd-2.4.29/modules/filters

include $(top_srcdir)/build/special.mk

